"""Add versioning to ai_logs

Revision ID: 28bfc0e851c6
Revises: 8c89652c423b
Create Date: 2026-08-19 05:29:40.431863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28bfc0e851c6'
down_revision: Union[str, None] = '8c89652c423b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_logs', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('ai_logs', sa.Column('prompt_version', sa.String(), nullable=True))
    op.add_column('ai_logs', sa.Column('generation_config', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'ai_logs', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_logs', type_='foreignkey')
    op.drop_column('ai_logs', 'generation_config')
    op.drop_column('ai_logs', 'prompt_version')
    op.drop_column('ai_logs', 'job_id')
    # ### end Alembic commands ###
