"""Add advanced logging fields to ai_logs

Revision ID: 32cae1734f4e
Revises: 28bfc0e851c6
Create Date: 2026-08-19 05:47:21.930732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32cae1734f4e'
down_revision: Union[str, None] = '28bfc0e851c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_logs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_logs', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_logs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_logs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('ai_logs', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('ai_logs', sa.Column('cost_estimate', sa.Float(), nullable=True))
    op.drop_column('ai_logs', 'tokens_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_logs', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ai_logs', 'cost_estimate')
    op.drop_column('ai_logs', 'error')
    op.drop_column('ai_logs', 'latency_ms')
    op.drop_column('ai_logs', 'total_tokens')
    op.drop_column('ai_logs', 'output_tokens')
    op.drop_column('ai_logs', 'prompt_tokens')
    # ### end Alembic commands ###
