"""Add job progress fields

Revision ID: a6e2edd920b1
Revises: 36291a7861a4
Create Date: 2026-08-20 15:37:41.104327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e2edd920b1'
down_revision: Union[str, None] = '36291a7861a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('percent', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'percent')
    # ### end Alembic commands ###
